trigger:
  branches:
    include:
      - develop

pool: Robert-PC_Agent

variables:
  node_version: '16.x'
  app_dir: '$(Build.SourcesDirectory)\Frontend'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      npm cache clean --force
      npm ci
      npx run build
    displayName: 'Install dependencies and Build the Vite app'
    workingDirectory: $(app_dir)

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['createArtifact'], true))
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Airlegance_Frontend.zip'
      ArtifactName: 'Airlegance_Frontend_Artifact'
    displayName: Publish Airlegance Frontend archive
